# Generated by Django 5.1.3 on 2024-11-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendshiprequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(choices=[('notsend', 'NotSent'), ('send', 'Send'), ('waiting', 'Waiting'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancel', 'Cancel')], default='notsend', max_length=20),
        ),
    ]
